spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 1000

  h2:
    console:
      enabled: true



logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

decorator:
  datasource:
    p6spy:
      enable-logging: 'true'