spring:
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: true
  datasource:
        hikari:
          maximum-pool-size: 50 # 커넥션 풀 크기
  profiles:
    active:
       - local
    group:
      local:
        - email
        - jwt
        - login
        - redis
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      data-locations: classpath*:data.sql
      mode: always
  web:
    resources:
      static-locations: classpath:/static/  # 정적 리소스 경로

  servlet:
    multipart:
      maxFileSize: 20MB   # 파일 한 개당 최대 사이즈
      maxRequestSize: 100MB  # 요청당 최대 파일 크기

  # 타임리프
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


# 상품 이미지 업로드 경로
itemImgLocation: C:/shop/item

  # 리소스 업로드 경로
uploadPath: file:///C:/shop/

# S3 설정
cloud:
  aws:
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
    s3:
      bucket: ${cloud.aws.s3.bucket}
    region:
      static: ${cloud.aws.region.static}
    stack:
      auto: false

# 토스페이먼츠
payment:
    toss:
      test_client_api_key : test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm
      test_secrete_api_key : test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
      success_url : "http://localhost:8080/api/v1/payments/toss/success"
      fail_url : "http://localhost:8080/api/v1/payments/toss/fail"