spring:
  sql:
    init:
      mode: always
      data-locations: classpath*:data.sql
      schema-locations: classpath*:schema.sql # mysql -> data.sql 실제 더미도 주석처리해야함
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
        connection.isolation: 2
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc:
        fetch_size: 50
        batch_size: 500 # mysql
        generate_statistics: true
        use_sql_comments: true
        order_updates: true
        order_inserts: true
        jdbc.time_zone: UTC