spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}


    hikari:
      minimum-idle: 10
      maximum-pool-size: 103
      idle-timeout: 30000
      connection-timeout: 60000
      max-lifetime: 1800000
      data-source-properties:
        connectionInitSql: SET GLOBAL innodb_print_all_deadlocks=1
        isolationLevel: READ_COMMITTED
        lockTimeout: 10000

  jpa:
    show-sql: true
    properties:
      hibernate:
      jdbc:
          lob:
            non_contextual_creation: true
          connection.isolation: 2
          format_sql: true
          default_batch_fetch_size: 1000
          jdbc:
          fetch_size: 50
          batch_size: 500 # mysql
          generate_statistics: true
          use_sql_comments: true
          order_updates: true
          order_inserts: true
          jdbc.time_zone: UTC


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG
          spi: TRACE
        event: TRACE

decorator:
  datasource:
    p6spy:
      enable-logging: 'true'

management:
  endpoints:
    web:
      exposure:
        include: "*" # 모든 관리 엔드포인트 활성화

actuator:
  metrics:
    enable:
      all: true
  traces:
    max-trace-count: 100 # 요청 및 응답 추적 제한

cloud:
  aws:
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
    s3:
      bucket: ${cloud.aws.s3.bucket}
    region:
      static: ${cloud.aws.region.static}
    stack:
      auto: false

