### 회원가입 페이지 진입
GET http://localhost:8080/member/join

### 약관 동의
POST http://localhost:8080/api/member/terms-next
Content-Type: application/json

[
  {
    "no" : 2,
    "name" : "만 14세 이상입니다",
    "agreeYn" : "Y",
    "level" : 2,
    "termsYn" : "Y"
  },
  {
    "no" : 3,
    "name" : "이용약관 동의",
    "agreeYn" : "Y",
    "level" : 2,
    "termsYn" : "Y"
  },
  {
    "no" : 5,
    "name" : "광고성 정보 수신 동의",
    "agreeYn" : "Y",
    "level" : 3,
    "termsYn" : "N"
  }
]

### 이메일 중복확인
POST http://localhost:8080/api/member/email-check
Content-Type: application/json

{
  "id": "gnstm831@gmail.com"
}

### 이메일 인증번호 발송
POST http://localhost:8080/api/mail/send?loginId=gnstm831@gmail.com
Content-Type: application/json

{
  "id": "gnstm831@gmail.com"
}

### 이메일 인증번호 확인
POST http://localhost:8080/api/mail/verify
Content-Type: application/json

{
  "loginId": "gnstm831@gmail.com",
  "verificationCode": "79GHS2"
}

### 이메일 입력 후 다음 회원가입 절차로 넘어간다.
POST http://localhost:8080/api/member/register
Content-Type: application/json

{
  "id": "gnstm831@gmail.com",
  "pwd": "TestPassword123!",
  "name": "안정훈",
  "phoneNum": "010-1234-5678",
  "birth": "1999-01-01",
  "gender": "F"
}

### 회원가입한 아이디와 비밀번호로 로그인 한다.
POST http://localhost:8080/api/login/member
Content-Type: application/json

{
  "loginId": "gnstm831@gmail.com",
  "pwd": "TestPassword123!",
  "autoLogin" : ""
}


### 마이페이지의 회원정보 페이지에 들어가서 비밀번호를 재입력하여 인증을 한다.
POST http://localhost:8080/api/mypage/confirm-password
Content-Type: application/json
access: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnbnN0bTgzMUBnbWFpbC5jb20iLCJjYXRlZ29yeSI6ImFjY2VzcyIsIm5hbWUiOiLslYjsoJXtm4giLCJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9VU0VSIn1dLCJpYXQiOjE3MzMzOTQ4NDEsImV4cCI6MTczMzM5ODQ0MX0.Qw9ccImp68IlQYNYFK0IYHs8S3teIBFR0HYGJ1XSOGM_48s0IHjVgkeQK1NAxi3WKQ-MspTarEEO9b1LzB32Lw

{
  "pwd": "TestPassword123!"
}

### 마이페이지에서 회원이 자신의 주소를 등록한다.
PUT http://localhost:8080/api/address/edit
Content-Type: application/json
access: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnbnN0bTgzMUBnbWFpbC5jb20iLCJjYXRlZ29yeSI6ImFjY2VzcyIsIm5hbWUiOiLslYjsoJXtm4giLCJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9VU0VSIn1dLCJpYXQiOjE3MzMzOTQ4NDEsImV4cCI6MTczMzM5ODQ0MX0.Qw9ccImp68IlQYNYFK0IYHs8S3teIBFR0HYGJ1XSOGM_48s0IHjVgkeQK1NAxi3WKQ-MspTarEEO9b1LzB32Lw

{
  "zipCode": "12345",
  "addressMain": "서울특별시 강남구 미왕빌딩",
  "addressDetail": "10층"
}
